/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlLoginView.java
 *
 * Created on 19-mrt-2011, 16:08:17
 */

package mastermind.panels;

import mastermind.controls.BPanel;
import mastermind.events.request.RequestEvent;

/**
 *
 * @author Bram
 */
public class PnlLoginView extends BPanel {

    /** Creates new form PnlLoginView */
    public PnlLoginView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername1 = new javax.swing.JTextField();
        btnLogin = new javax.swing.JLabel();
        btnGoBack = new javax.swing.JLabel();
        btnRegister = new javax.swing.JLabel();
        lblAchtergrond = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(PnlLoginView.class);
        txtPassword.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.setBounds(320, 330, 150, 20);
        jLayeredPane1.add(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtUsername1.setName("txtUsername1"); // NOI18N
        txtUsername1.setBounds(320, 220, 150, 20);
        jLayeredPane1.add(txtUsername1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnLogin.setText(resourceMap.getString("btnLogin.text")); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setName("btnLogin"); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.setBounds(350, 390, 100, 40);
        jLayeredPane1.add(btnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGoBack.setText(resourceMap.getString("btnGoBack.text")); // NOI18N
        btnGoBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGoBack.setName("btnGoBack"); // NOI18N
        btnGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGoBackMouseClicked(evt);
            }
        });
        btnGoBack.setBounds(620, 540, 160, 40);
        jLayeredPane1.add(btnGoBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnRegister.setText(resourceMap.getString("btnRegister.text")); // NOI18N
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        btnRegister.setBounds(620, 470, 160, 40);
        jLayeredPane1.add(btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAchtergrond.setIcon(resourceMap.getIcon("lblAchtergrond.icon")); // NOI18N
        lblAchtergrond.setText(resourceMap.getString("lblAchtergrond.text")); // NOI18N
        lblAchtergrond.setName("lblAchtergrond"); // NOI18N
        lblAchtergrond.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(lblAchtergrond, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGoBackMouseClicked
        fireRequestEvent(new RequestEvent(this, "show:main"));

    }//GEN-LAST:event_btnGoBackMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
         fireRequestEvent(new RequestEvent(this, "conn:login"));
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        fireRequestEvent(new RequestEvent(this, "show:register"));
    }//GEN-LAST:event_btnRegisterMouseClicked

    public String getUserName()
    {
        return txtUsername1.getText();
    }

    public String getPassword()
    {
        return "" + new String(txtPassword.getPassword());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnGoBack;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAchtergrond;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername1;
    // End of variables declaration//GEN-END:variables

}
