/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MasterMindPion.java
 *
 * Created on 5-mrt-2011, 18:43:27
 */

package mastermind.controls;

import java.awt.Color;

/**
 *
 * @author Bram
 */
public class MasterMindPion extends javax.swing.JPanel {

    int amountOfColors=6;
    int currentColor=1;
    boolean enabled=true;


    /** Creates new form MasterMindPion */
    public MasterMindPion() {
        initComponents();
        this.setBackground(new Color(255,255,255,0));
    }

    public int getAmountOfColors() {
        return amountOfColors;
    }

    public void setAmountOfColors(int amountOfColors) {
        this.amountOfColors = amountOfColors;
    }

    public int getCurrentColor() {
        return currentColor;
    }

    public void setCurrentColor(int currentColor) {
        this.currentColor = currentColor;
        setToColor(currentColor);
    }

    private void setToColor(int number)
    {
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(MasterMindPion.class);
        if (number==1)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon"));
        }
        else if (number==2)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon2"));
        }
        else if (number==3)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon3"));
        }
        else if (number==4)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon4"));
        }
        else if (number==5)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon5"));
        }
        else if (number==6)
        {
            imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon6"));
        }
    }

    private void nextColor()
    {
        currentColor++;
        if (currentColor >amountOfColors)
        {
            currentColor=1;
        }
        setToColor(currentColor);
    }

    @Override
    public void setEnabled(boolean enabled)
    {
        this.enabled=enabled;
    }







    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgKnop = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(MasterMindPion.class);
        imgKnop.setIcon(resourceMap.getIcon("imgKnop.icon")); // NOI18N
        imgKnop.setText(resourceMap.getString("imgKnop.text")); // NOI18N
        imgKnop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgKnop.setName("imgKnop"); // NOI18N
        imgKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgKnopMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgKnop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgKnop)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imgKnopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgKnopMouseClicked
        if (enabled)
        {
            nextColor();
        }
    }//GEN-LAST:event_imgKnopMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgKnop;
    // End of variables declaration//GEN-END:variables

}
