/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MasterMindRow.java
 *
 * Created on 5-mrt-2011, 19:21:38
 */

package mastermind.controls;

import java.awt.Color;

/**
 *
 * @author Bram
 */
public class MasterMindRow extends javax.swing.JPanel {

    /** Creates new form MasterMindRow */
    public MasterMindRow() {
        initComponents();

        this.setBackground(new Color(255,255,255,0));

    }
    

    public void setColors(String combinatie)
    {
        masterMindPion1.setCurrentColor(Integer.parseInt(combinatie.substring(0,1)));
        masterMindPion2.setCurrentColor(Integer.parseInt(combinatie.substring(1,2)));
        masterMindPion3.setCurrentColor(Integer.parseInt(combinatie.substring(2,3)));
        masterMindPion4.setCurrentColor(Integer.parseInt(combinatie.substring(3,4)));
    }

    public String getColors()
    {
        String str;
        str=""+masterMindPion1.getCurrentColor()+masterMindPion2.getCurrentColor()+masterMindPion3.getCurrentColor()+masterMindPion4.getCurrentColor();
        return str;
    }

    public int getAmountOfColors()
    {
        return masterMindPion1.getAmountOfColors();
    }
    
    public void setAmountOfColors(int amount)
    {
        masterMindPion1.setAmountOfColors(amount);
        masterMindPion2.setAmountOfColors(amount);
        masterMindPion3.setAmountOfColors(amount);
        masterMindPion4.setAmountOfColors(amount);
    }

    @Override
    public void setEnabled(boolean value)
    {
        masterMindPion1.setEnabled(value);
        masterMindPion2.setEnabled(value);
        masterMindPion3.setEnabled(value);
        masterMindPion4.setEnabled(value);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        masterMindPion1 = new mastermind.controls.MasterMindPion();
        masterMindPion2 = new mastermind.controls.MasterMindPion();
        masterMindPion3 = new mastermind.controls.MasterMindPion();
        masterMindPion4 = new mastermind.controls.MasterMindPion();

        setName("Form"); // NOI18N

        masterMindPion1.setName("masterMindPion1"); // NOI18N

        masterMindPion2.setName("masterMindPion2"); // NOI18N

        masterMindPion3.setName("masterMindPion3"); // NOI18N

        masterMindPion4.setName("masterMindPion4"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(masterMindPion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masterMindPion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masterMindPion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(masterMindPion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masterMindPion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterMindPion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterMindPion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(masterMindPion4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mastermind.controls.MasterMindPion masterMindPion1;
    private mastermind.controls.MasterMindPion masterMindPion2;
    private mastermind.controls.MasterMindPion masterMindPion3;
    private mastermind.controls.MasterMindPion masterMindPion4;
    // End of variables declaration//GEN-END:variables

}
