/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlLoadingView.java
 *
 * Created on 19-mrt-2011, 17:02:41
 */

package mastermind.panels;

import mastermind.controls.BPanel;

/**
 *
 * @author Bram
 */
public class PnlLoadingView extends BPanel {

    /** Creates new form PnlLoadingView */
    public PnlLoadingView() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAchtergrond = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(PnlLoadingView.class);
        lblAchtergrond.setIcon(resourceMap.getIcon("lblAchtergrond.icon")); // NOI18N
        lblAchtergrond.setText(resourceMap.getString("lblAchtergrond.text")); // NOI18N
        lblAchtergrond.setName("lblAchtergrond"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAchtergrond)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAchtergrond)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAchtergrond;
    // End of variables declaration//GEN-END:variables


}
