/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlMainView.java
 *
 * Created on 5-mrt-2011, 13:34:08
 */

package mastermind.panels;

import mastermind.controls.BPanel;
import mastermind.events.request.RequestEvent;

/**
 *
 * @author Bram
 */
public class PnlMainView extends BPanel {

    /** Creates new form PnlMainView */
    public PnlMainView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnMultiPlayer = new javax.swing.JLabel();
        btnSinglePlayer = new javax.swing.JLabel();
        lblAchterGrond = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(800, 600));

        btnMultiPlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMultiPlayer.setName("btnMultiPlayer"); // NOI18N
        btnMultiPlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiPlayerMouseClicked(evt);
            }
        });
        btnMultiPlayer.setBounds(280, 350, 240, 50);
        jLayeredPane1.add(btnMultiPlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnSinglePlayer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSinglePlayer.setName("btnSinglePlayer"); // NOI18N
        btnSinglePlayer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSinglePlayerMouseClicked(evt);
            }
        });
        btnSinglePlayer.setBounds(280, 300, 240, 50);
        jLayeredPane1.add(btnSinglePlayer, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(PnlMainView.class);
        lblAchterGrond.setIcon(resourceMap.getIcon("lblAchterGrond.icon")); // NOI18N
        lblAchterGrond.setName("lblAchterGrond"); // NOI18N
        lblAchterGrond.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(lblAchterGrond, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSinglePlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSinglePlayerMouseClicked
        fireRequestEvent(new RequestEvent(this, "show:singleplayer"));
}//GEN-LAST:event_btnSinglePlayerMouseClicked

    private void btnMultiPlayerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiPlayerMouseClicked
        fireRequestEvent(new RequestEvent(this, "show:login"));
    }//GEN-LAST:event_btnMultiPlayerMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnMultiPlayer;
    private javax.swing.JLabel btnSinglePlayer;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAchterGrond;
    // End of variables declaration//GEN-END:variables

}
