/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlRegisterView.java
 *
 * Created on 9-apr-2011, 16:20:21
 */

package mastermind.panels;

import mastermind.controls.BPanel;
import mastermind.events.request.RequestEvent;

/**
 *
 * @author Bram
 */
public class PnlRegisterView extends BPanel {

    /** Creates new form PnlRegisterView */
    public PnlRegisterView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnRegister = new javax.swing.JLabel();
        btnBack = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtEmail = new javax.swing.JTextField();
        lblAchterGrond = new javax.swing.JLabel();

        setName("Form"); // NOI18N

        jLayeredPane1.setName("jLayeredPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(mastermind.MasterMindApp.class).getContext().getResourceMap(PnlRegisterView.class);
        btnRegister.setText(resourceMap.getString("btnRegister.text")); // NOI18N
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.setName("btnRegister"); // NOI18N
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegisterMouseClicked(evt);
            }
        });
        btnRegister.setBounds(620, 460, 160, 60);
        jLayeredPane1.add(btnRegister, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnBack.setText(resourceMap.getString("btnBack.text")); // NOI18N
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setName("btnBack"); // NOI18N
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });
        btnBack.setBounds(620, 530, 160, 50);
        jLayeredPane1.add(btnBack, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtUsername.setText(resourceMap.getString("txtUsername.text")); // NOI18N
        txtUsername.setName("txtUsername"); // NOI18N
        txtUsername.setBounds(320, 220, 150, 20);
        jLayeredPane1.add(txtUsername, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtPassword.setText(resourceMap.getString("txtPassword.text")); // NOI18N
        txtPassword.setName("txtPassword"); // NOI18N
        txtPassword.setBounds(320, 330, 150, 20);
        jLayeredPane1.add(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtEmail.setText(resourceMap.getString("txtEmail.text")); // NOI18N
        txtEmail.setName("txtEmail"); // NOI18N
        txtEmail.setBounds(320, 430, 150, 20);
        jLayeredPane1.add(txtEmail, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblAchterGrond.setIcon(resourceMap.getIcon("lblAchterGrond.icon")); // NOI18N
        lblAchterGrond.setText(resourceMap.getString("lblAchterGrond.text")); // NOI18N
        lblAchterGrond.setName("lblAchterGrond"); // NOI18N
        lblAchterGrond.setBounds(0, 0, 800, 600);
        jLayeredPane1.add(lblAchterGrond, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseClicked
        // Register
        fireRequestEvent(new RequestEvent(this, "regi:registerplayer"));
    }//GEN-LAST:event_btnRegisterMouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // Back
        fireRequestEvent(new RequestEvent(this, "show:login"));
    }//GEN-LAST:event_btnBackMouseClicked

    public String getUsername()
    {
        return txtUsername.getText();
    }
        //the password is kinda weird so we'll make it a string..
    public String getPassword()
    {
        return "" + new String(txtPassword.getPassword());
    }

    public String getEmail()
    {
        return txtEmail.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JLabel btnRegister;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblAchterGrond;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
